version: '3'

networks:
  main:

volumes:
  data:
  webapp:
  mongodata:

services:
  apiserver:
    restart: unless-stopped
    environment:
      DEBUG: 0
      MONGO_HOST: "mongo"
      MONGO_PORT: "27017"
    image: moritzs/pavooc:latest
    # build: .
    volumes:
      - data:/usr/app/data
    command: ["python", "-m", "pavooc.server.main"]
    # volumes:
    #   - .:/usr/app
    networks:
      - main
  nginx:
    restart: unless-stopped
    environment:
      DEBUG: 0
    build:
      context: ./nginx
    ports:
      - '${EXPOSED_PORT}:80' # expose 80 on host and send to 80 in container
    volumes:
      - webapp:/usr/app/webapp/build
      - data:/usr/app/data
    networks:
      - main
    depends_on:
      - apiserver

  mongo:
    restart: unless-stopped
    volumes:
      - mongodata:/data/db
    image: mongo:latest
    networks:
      - main

  data-processing:
    image: moritzs/pavooc:latest
    # build: .
    environment:
      JAVA_RAM: '4'
      COMPUTATION_CORES: '6'
      MONGO_HOST: "mongo"
      MONGO_PORT: "27017"
      DEBUG: 0
      GENOME: "cs1.1"
      ONLY_INIT: 0
    command: ["python", "-m", "pavooc.pipeline"] 
    #command: ["echo", "data processing done"]
    volumes:
      #- data:/usr/app/data
      - .:/usr/app
    networks:
      - main
    depends_on:
      - mongo

  build-website:
    image: moritzs/pavooc:latest
    # build: .
    command: ["bash", "-c", "npm install && npm run build"]
    working_dir: /usr/app/webapp
    volumes:
      - webapp:/usr/app/webapp/build
      - data:/usr/app/data
