version: '3'

networks:
  main:

volumes:
  data:
  webapp:

services:
  apiserver:
    environment:
      MONGO_HOST: "mongo:27017"
    image: moritzs/pavooc:20171129
    volumes:
      - data:/usr/app/data
    command: ["python", "-m", "pavooc.server.main"]
    # volumes:
    #   - .:/usr/app
    networks:
      - main
  nginx:
    image: nginx:1.11 # this will use the latest version of 1.11.x
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - webapp:/usr/app/webapp/build
    networks:
      - main
    depends_on:
      - apiserver

  mongo:
    image: mongo:latest
    networks:
      - main

  data-processing:
    image: moritzs/pavooc:20171129
    environment:
      MONGO_HOST: "mongo:27017"
    #command: ["python", "-m", "pavooc.pipeline"]
    command: ["echo", "data processing done"]
    volumes:
      - data:/usr/app/data

  build-website:
    image: moritzs/pavooc:20171129
    command: ["bash", "-c", "npm install && npm run build"]
    working_dir: /usr/app/webapp
    volumes:
      - webapp:/usr/app/webapp/build
