version: '3'

networks:
  main:

volumes:
  data:
  webapp:
  mongodata:

services:
  apiserver:
    environment:
      DEBUG: 0
      MONGO_HOST: "mongo:27017"
    image: moritzs/pavooc:latest
    # build: .
    volumes:
      - data:/usr/app/data
    command: ["python", "-m", "pavooc.server.main"]
    # volumes:
    #   - .:/usr/app
    networks:
      - main
  nginx:
    environment:
      DEBUG: 0
    build:
      context: ./nginx
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
    volumes:
      - webapp:/usr/app/webapp/build
      - data:/usr/app/data
    networks:
      - main
    depends_on:
      - apiserver

  mongo:
    volumes:
      - mongodata:/data/db
    image: mongo:latest
    networks:
      - main

  data-processing:
    image: moritzs/pavooc:latest
    # build: .
    environment:
      JAVA_RAM: '1'
      COMPUTATION_CORES: '1'
      MONGO_HOST: "mongo:27017"
      DEBUG: 0
    command: ["python", "-m", "pavooc.pipeline"]
    #command: ["echo", "data processing done"]
    volumes:
      - data:/usr/app/data
    networks:
      - main

  build-website:
    image: moritzs/pavooc:latest
    # build: .
    command: ["bash", "-c", "npm install && npm run build"]
    working_dir: /usr/app/webapp
    volumes:
      - webapp:/usr/app/webapp/build
      - data:/usr/app/data
