export const FETCH_KNOCKOUTS = 'IO/FETCH_KNOCKOUTS';
export const FETCH_KNOCKOUTS_SUCCESS = 'IO/FETCH_KNOCKOUTS_SUCCESS';
export const FETCH_KNOCKOUTS_FAILURE = 'IO/FETCH_KNOCKOUTS_FAILURE';
export const INITIAL_LOAD = 'IO/INITIAL_LOAD';
export const INITIAL_LOAD_SUCCESS = 'IO/INITIAL_LOAD_SUCCESS';
export const INITIAL_LOAD_FAILURE = 'IO/INITIAL_LOAD_FAILURE';
